export const CHANGE = 'CHANGE';

export const ActionTypes = {
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  CREATE_PROJECT: 'CREATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  CREATE_SIMULATION: 'CREATE_SIMULATION',
  UPDATE_SIMULATION: 'UPDATE_SIMULATION',
  DELETE_SIMULATION: 'DELETE_SIMULATION'
};
